name       : cython
version    : 0.29.35
release    : 30
source     :
    - https://github.com/cython/cython/archive/refs/tags/0.29.35.tar.gz : a2da56cc22be823acf49741b9aa3aa116d4f07fa8e8b35a3cb08b8447b37c607
license    : Apache-2.0
component  : programming
summary    : Compiler for Python and Cython
description: |
    Cython is an optimising static compiler for Python and Cython, making writing C extensions for Python as easy as Python itself. It allows you to write callbacks from and to C or C++ natively, tune Python into C performance, work efficiently with large datasets, and more.
builddeps  :
    - pkgconfig(python3)
    - numpy             # check
    - python-coverage   # check
    - python-jedi       # check
rundeps    :
    - python-devel
    - python3-devel
build      : |
    %python3_setup
    %python_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    # The checks last like... forever. Feel free to uncomment them to check the package
#    %python_test runtests.py -v
#    %python3_test runtests.py -v
