name       : cython
version    : 0.29.32
release    : 29
source     :
    - https://github.com/cython/cython/releases/download/0.29.32/Cython-0.29.32.tar.gz : 8733cf4758b79304f2a4e39ebfac5e92341bce47bcceb26c1254398b2f8c1af7
license    : Apache-2.0
component  : programming
summary    : Compiler for Python and Cython
description: |
    Cython is an optimising static compiler for Python and Cython, making writing C extensions for Python as easy as Python itself. It allows you to write callbacks from and to C or C++ natively, tune Python into C performance, work efficiently with large datasets, and more.
builddeps  :
    - pkgconfig(python3)
    - numpy             # check
    - python-coverage   # check
    - python-jedi       # check
rundeps    :
    - python-devel
    - python3-devel
build      : |
    %python3_setup
    %python_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    # The checks last like... forever. Feel free to uncomment them to check the package
#    %python_test runtests.py -v
#    %python3_test runtests.py -v
