name       : cython
version    : 0.29.30
release    : 28
source     :
    - https://github.com/cython/cython/releases/download/0.29.30/Cython-0.29.30.tar.gz : 2235b62da8fe6fa8b99422c8e583f2fb95e143867d337b5c75e4b9a1a865f9e3
license    : Apache-2.0
component  : programming
summary    : Compiler for Python and Cython
description: |
    Cython is an optimising static compiler for Python and Cython, making writing C extensions for Python as easy as Python itself. It allows you to write callbacks from and to C or C++ natively, tune Python into C performance, work efficiently with large datasets, and more.
builddeps  :
    - pkgconfig(python3)
    - numpy             # check
    - python-coverage   # check
    - python-jedi       # check
rundeps    :
    - python-devel
    - python3-devel
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
#check      : |
#    # The checks last like... forever. Feel free to uncomment them to check the package
#    %python_test runtests.py -v
#    %python3_test runtests.py -v
