name       : cython
version    : 0.25.2
release    : 7
source     :
    - https://github.com/cython/cython/archive/0.25.2.tar.gz : 206b6fc7e8cebe8e0529064a92e4f53f13a8f1d1f4dc173c32782ab134a2551e
license    : Apache-2.0
component  : programming
summary    : Compiler for Python and Cython
description: |
    Cython is an optimising static compiler for Python and Cython, making writing C extensions for Python as easy as Python itself. It allows you to write callbacks from and to C or C++ natively, tune Python into C performance, work efficiently with large datasets, and more.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
