name       : cython
version    : 0.28.3
release    : 14
source     :
    - https://github.com/cython/cython/archive/0.28.3.tar.gz : 05e3eb7f06043f5ff2028338370329e71c29f57315e95f4dc6ad7c4971dd4c6f
license    : Apache-2.0
component  : programming
summary    : Compiler for Python and Cython
description: |
    Cython is an optimising static compiler for Python and Cython, making writing C extensions for Python as easy as Python itself. It allows you to write callbacks from and to C or C++ natively, tune Python into C performance, work efficiently with large datasets, and more.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-devel
    - python3-devel
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
