name       : cython
version    : 0.27.1
release    : 10
source     :
    - https://github.com/cython/cython/archive/0.27.1.tar.gz : 87d7c24f761dd8f00062706fe3c4375b3fb155fae7b0d117702636c55aa4e985
license    : Apache-2.0
component  : programming
summary    : Compiler for Python and Cython
description: |
    Cython is an optimising static compiler for Python and Cython, making writing C extensions for Python as easy as Python itself. It allows you to write callbacks from and to C or C++ natively, tune Python into C performance, work efficiently with large datasets, and more.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-devel
    - python3-devel
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
