name       : cython
version    : 0.27.2
release    : 11
source     :
    - https://github.com/cython/cython/archive/0.27.2.tar.gz : 2fa7bc2581b56cb01012d7f0c145bf6fd053f8f0e5445275f014e40c2bce65cb
license    : Apache-2.0
component  : programming
summary    : Compiler for Python and Cython
description: |
    Cython is an optimising static compiler for Python and Cython, making writing C extensions for Python as easy as Python itself. It allows you to write callbacks from and to C or C++ natively, tune Python into C performance, work efficiently with large datasets, and more.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-devel
    - python3-devel
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
