name       : cython
version    : 0.29.1
release    : 16
source     :
    - https://github.com/cython/cython/archive/0.29.1.tar.gz : fab6796e5a5fb6e2f860c7d8180479dade01dfbebaf490a213c3e312a3a278d8
license    : Apache-2.0
component  : programming
summary    : Compiler for Python and Cython
description: |
    Cython is an optimising static compiler for Python and Cython, making writing C extensions for Python as easy as Python itself. It allows you to write callbacks from and to C or C++ natively, tune Python into C performance, work efficiently with large datasets, and more.
builddeps  :
    - pkgconfig(python3)
    - numpy             # check
    - python-coverage   # check
    - python-jedi       # check
rundeps    :
    - python-devel
    - python3-devel
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
#check      : |
#    # The checks last like... forever. Feel free to uncomment them to check the package
#    %python_test runtests.py -v
#    %python3_test runtests.py -v
